import createFetchClient from "openapi-fetch";
import type { paths, components, operations } from "./types/api"; // generated by openapi-typescript


export type api = {
  components: components;
  operations: operations;
  paths: paths;
}


type ApiOptions = {
  /**
   * The base URL of the AeroDB API.
   * 
   * @default "https://api.aerodb.net"
   */
  baseUrl?: string;
  /**
   * Additional headers to include in the API requests.
   */
  headers?: Record<string, string>;
}

/**
 * Return a new AeroDB client instance.
 * @param apiOptions 
 * @returns 
 */
export function createClient(apiOptions?:ApiOptions){
  return  createFetchClient<paths>({ baseUrl: apiOptions?.baseUrl || 'https://api.aerodb.net', headers: apiOptions?.headers });
}

