import createFetchClient from "openapi-fetch";
import type { paths } from "./types/api"; // generated by openapi-typescript

export * as api from "./types/api"; // re-export types for convenience

// 

type ApiOptions = {
  /**
   * The base URL of the AeroDB API.
   * 
   * @default "https://api.aerodb.net"
   */
  baseUrl?: string;
  /**
   * Additional headers to include in the API requests.
   */
  headers?: Record<string, string>;
}

/**
 * Return a new AeroDB client instance.
 * @param apiOptions 
 * @returns 
 */
export function createClient(apiOptions:ApiOptions){
  return  createFetchClient<paths>({ baseUrl: apiOptions.baseUrl || 'https://api.aerodb.net', headers: apiOptions.headers });
}

