name: On Release
on:
  release:
    types: [published]

jobs:
  ## WEB
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  publish:
    name: Publish Package to npmjs
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    needs: [build]
